### ISSUE TITLE
Re-Fraction issues 

### ISSUE THREAD

**Issue by Dominance** [TinyModularThings/Scavenge#1]
- Seems as if while using clicktype "break" and consume_block, the block gets replaced immediately and broken. making the two incompatible. example https://streamable.com/rz9so and the script used
```
{
  "block_pools": [{
    "name": "BreakIron",
    "type": {
      "type": "block",
      "name": "minecraft:iron_ore"
    },
    "clicktype": "break",
    "properties": [{
      "type": "consume_block",
      "chance": "100",
      "name": "minecraft:gold_ore",
      "meta": "0"
    }],
    "drops": [{
      "name": "minecraft:iron_nugget"
    }],
    "messages": [{
      "id": "success",
      "message": "it works yo"
    }]
  }]
}
```
- Drops do not populate into the world but are directly put into the players inventory. If players inventory is full, they player will not receive the assigned drop. This is not a only re-fraction issue but figured id keep it all in one.

**Comment by Dominance** [comment]
- so replicating this https://streamable.com/51m93 is impossible then :(

- I did not see it in the documentation, sorry about that. being under condition block properties got me! I am getting familiar with the system.

**Comment by Speiger** [comment]
1. Maybe its possible but not in the traditional way. I will look into that later.
2. Yeah please read the doc and if needed export it yourself since thats now a config.

**Comment by Dominance** [comment]
Have been away from Minecraft stuff due to work. Have you updated it to include a way to make #1 possible?

**Comment by Speiger** [comment]
the only thing that i can make is the thing cancable like the other things but right now its not a planned feature. Right now wont be possible until i make another update. Which will take a bit.
