### ISSUE TITLE
Can't use curly braces

### ISSUE THREAD

**Issue by randemail** [TinyModularThings/Scavenge#10]
In 1.12.2 I'm trying to use this but the curly braces cause problems.
{
	"type": "use_command",
	"name": "blockdata",
        "arguments": "~ ~ ~ { mode:3 }"
}

It's not a big problem but since I only saw a few people mention anything about editing block nbt, I thought I'd put it here.
I was going to use it to fix a small problem in my private pack anyway.

**Comment by Speiger** [comment]
Tried Escaping them? with \
So \{ mode:3 \}

This is technically not a Scavenge Problem but a JsonProblem.

**Comment by randemail** [comment]
(I normally put only one backslash but since I apparently need to escape it when writing here, I put an extra here.)
I tried it, I even tried this "\u007B mode:3 \u007D" but it didn't work.
When I used backslashes (like this "arguments": "~ ~ ~ \\{ mode:3 \\}") it didn't work at all and the printErrors command printed this:
com.google.gson.stream.MalformedJsonException: Invalid escape sequence at line 28 column 28 path $.block_pools[0].properties[2].arguments

When I used either \u007B or normal } the game crashes after launch.
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Scavenge (scavenge)
Caused by: java.lang.NullPointerException

edit: above I wrote "normal \" but I meant "normal }"

**Comment by Speiger** [comment]
I wonder what happens if you use '~ ~ ~ { mode:3 }' because i know Google/Json can handle that.

But if that does not work then i am sorry but this is a limitation of Json i can not fix.
Especially since i don't have the devspaces anymore. One of the reasons why no more patches came out for 1.10.2-1.12.2

**Comment by randemail** [comment]
I just tried that, didn't work.
Thanks anyway.
Also this mod helped me fix many things in my private modpack so thank you for making it.
