### ISSUE TITLE
has_item_tag causing datapack to not to be able to load

### ISSUE THREAD

**Issue by dozingpip** [TinyModularThings/Scavenge#12]
Small reproduction datapack used/referenced [custom_stuff.zip](https://github.com/TinyModularThings/Scavenge/files/6833967/custom_stuff.zip)
After starting up Minecraft fresh and loading a world, it displays the message "Errors in currently selected datapacks prevented the world from loading."
See [debug.log](https://github.com/TinyModularThings/Scavenge/files/6833977/debug.log) for more details on the error.

If I change the file extension of `custom_stuff/data/minecraft/scavenge_scripts/bad_pebble.json` to something like `bad_pebble.blah` (just so it doesn't try to load the file), and try again, I can load the world. If I then save and quit to menu, rename the file back to `bad_pebble.json`, and load the world again, no issues, the scavenge works fine as intended and everything. It also works fine if I just do a `/reload` after renaming the file.  So it specifically only seems to be an issue on the game's first loading of the datapack?

The only difference between `bad_pebble.json` and `pebble.json` (in scavenge_scripts of the attached datapack) is that I did `has_item_tag` on tag `minecraft:logs` for the first, and `has_item` on item `minecraft:stick` for the second.

Reproduced on an instance with only:
Global Data & Resourcepacks 1.7.4
JEI 7.7.1.110
Scavenge 2.0.2
Forge 36.1.35
Minecraft 1.16.5

Thanks!

**Comment by Speiger** [comment]
Thanks will be dealt with the next patch. Which should come out very soon. I already started a patch just hadn't had the time to finish it.

**Comment by Speiger** [comment]
Ok found the issue will be included in the next patch (once that one is done)

**Comment by Speiger** [comment]
(Eta is most likely next week because i still need to fix #11 and also some other projects still have priority over this)
