### ISSUE TITLE
"Errors in currently selected datapacks prevented world from loading" but datapack works fine when i add it afterwards

### ISSUE THREAD

**Issue by lerokko** [TinyModularThings/Scavenge#13]
I followed the 1.16 tutorial and used the datapack mod thing to auto load datapacks. but no matter what mod as soon as my script is in there it wont let me create a new world with it (whole datapack loads fine without it). If I how ever make a world without it and then just drop it in the datapack folder and do /reload it works just fine.

Using forge 36.1.66 fore 1.16.5 and latest version of scavenge

logfile: https://gist.github.com/lerokko/949615373e6de091b4781cb7a80e1ca9

script:

```
{
    "scripts": {
        "id": "minecraft:fiber",
        "swing": true,
        "drop_rule": "block",
        "properties": [
            {
				"property": "scavenge_player:has_item_tag",
				"tag": "minecraft:logs"
			},
            {
                "property": "scavenge_utils:conditional_effect",
                "test": {
                    "property": "scavenge_player:real_player"
                },
                "true": {
                    "property": "scavenge_player:add_exhaustion",
                    "exhaustion": 0.1
                },
                "false": {
                    "property": "scavenge_utils:default_effect"
                }
            },
            {
                "property": "scavenge_utils:conditional_effect",
                "test": {
                    "property": "scavenge_player:limit_action",
                    "id": "soundlimit",
                    "delay": 10,
                    "limit": [
                        {
                            "condition": "scavenge:smaller",
                            "value": 1
                        }
                    ],
                    "change": {
                        "operation": "scavenge:add",
                        "value": 1
                    }
                },
                "true": {
                    "property": "scavenge_utils:array_effect",
                    "effects": [
                        {
                            "property": "scavenge_world:play_sound",
                            "category": "block",
                            "sound": "minecraft:block.grass.hit",
                            "pitch": {
                               "operation": "scavenge:const",
                                "value": 100
                            }
                        },
                        {
                            "property": "scavenge_player:limit_action",
                            "id": "soundlimit",
                            "delay": 10,
                            "limit": [
                                {
                                    "condition": "scavenge:smaller",
                                    "value": 1
                                }
                            ],
                            "change": {
                                "operation": "scavenge:add",
                                "value": 1
                            }
                        }
                    ]
                },
                "false": {
                    "property": "scavenge_utils:default_effect"
                }
            },
            {
                "property": "scavenge_world:spawn_particles",
                "particle": "minecraft:crit",
                "count": {
		    "operation": "scavenge:const",
		    "value": 3
	       }
            },
			{
				"property": "scavenge_player:damage_item",
				"amount": 1,
				"chance": 100.0
			}
        ],
        "loot": [
            {
                "lootPool": "minecraft:fiber",
                "conditions": [
                    {
                        "property": "scavenge_utils:random",
                        "chance": 85.0
                    }
                ]
            }
        ],
        "type": {
            "type": "right_click",
            "consume": false,
            "show": true
        },
        "targets": [
            {
                "type": "blocks",
                "id": [
                    "minecraft:grass",
                    "minecraft:fern"
                ]
            }
        ]
    }
}
```

**Comment by Speiger** [comment]
You have hundreds of Errors during world creation. This could be scavenges fault or not. I am not sure but none of them arent even related to scavenge AT ALL (otherwise scavenge would be visible because no Mixins or Code Editing in it)

```
[02:01:54] [Render thread/ERROR]: Parsing error loading recipe yurinas_enderite_mod:enderite_chestplate_rg
com.google.gson.JsonSyntaxException: Unknown item 'gildedarmor:gilded_netherite_chestplate'
```

Please make sure they are not the problem.

**Comment by lerokko** [comment]
I know its errors galore. This might be an emergent property or Smt but the thing is removing that single script i made from the datapack makes the whole game run fine and world creation. So i thought it be the cause. You recommend doing a binary(ish) search to see when it stops working?

**Comment by Speiger** [comment]
Kinda. How about you use the "Internal" add datapack feature on the "createWorldScreen" and see if it happens there? Because datapacks get tested before the world actually allows you to use them. And scavenge scripts too so if there is a error the screen for single player worlds should automatically deny you inserting it. And it should throw a error in the logs to if that happens.

And if that is fine then maybe try another "add resource packs mod" and if that is fine then we know the issue. If not then we have seen scavenge is potentionally the issue and i have a "testcase" that i can work with.

(When using the add datapack feature from create new world screen happens make sure the auto add datapack mod is not included)

**Comment by lerokko** [comment]
I already tested Copy-Paste and Openloader as well. None work. those were all I could find.
I added the datapack during world creation the the datapack menu as you suggested. The "Validating datapack" screen passed successfully and I could just create and join the world. The script also works and the datapack is enabled.

**Comment by Speiger** [comment]
Hmmm so it is not a "Scavenge Problem" but a datapack addition problem via the auto loaders?

**Comment by lerokko** [comment]
I was hoping that one of the 3 autoloader would do it differently and one method would work. But seems like the way they are implemented does not work with some of my mods, maybe, not sure. They are not using the method that minecraft implemented in the world creation GUI, cause that works. The autoloader works with datapacks that don't have scavenge_scripts, but that does not mean its Scavenges fault. It could be the autoloader or it could be another mod messing with either one of them.
