### ISSUE TITLE
Allow me to port?

### ISSUE THREAD

**Issue by Gurkysword12** [TinyModularThings/Scavenge#19]
Speiger would you allow me to port this mod on this github repository? The license is ARR so dont want to make a seperate mod but also kinda need this for my pack

Mods ive worked on NeverEnderOre, AutosmithingTable and unreleased ones. 
So would u allow me to work on this mod? If yes add me to the organization and repository

**Comment by Speiger** [comment]
Project is Closed Source.
So hard to do even if you are added to the project.

Also not sure.
Right now i am prioritizing ic2c once that is done i will look into it.
