### ISSUE TITLE
damage_item Property Defaults to Offhand

### ISSUE THREAD

**Issue by Murdermancer** [TinyModularThings/Scavenge#2]
Hey! Loving this mod!

I noticed that the damage_item property defaults to damaging the item in the offhand.

`"offHand": (If the Item should be damaged from the Main or OffHand, Default: false) Boolean,`

If offhand is false, I'd think that would mean that it points to the main hand?

Not sure if this is the intended behaviour or not, but thought I'd point it out.

**Comment by Speiger** [comment]
already aware. Next patch to have that fixed.
