### ISSUE TITLE
[1.19.2-2.0.0] Crashing when entering world creation menu

### ISSUE THREAD

**Issue by pouchrat** [TinyModularThings/Scavenge#20]
When Scavenge 2.0.0 is installed, the game crashes after entering world creation menu. World creation menu loads fine without mods and with other mods, but not Scavenge.

Minecraft version:
1.19.2
Java version:
17.0.1
Forge version:
43.2.0

Crash reports:
[Prism Launcher](https://mclo.gs/xxiOQNT) | [Vanilla Launcher (Curseforge)](https://mclo.gs/dLKfqpg)

**Comment by Speiger** [comment]
These Crashlogs do not contain scavenge code at all.
Sooo not sure if thats the issue.

**Comment by pouchrat** [comment]
Yeah, I did notice that, but I can't think of what else it could be cuz the only difference is whether or not Scavenge is installed.

**Comment by Speiger** [comment]
wouldn't wonder if your forge version is to new or to old...

**Comment by pouchrat** [comment]
It's possible. I'm using Forge 43.2.0 (the latest version), and I did try a couple older versions, but had the same issue. Is there a specific Forge version that you know works with 2.0.0?

**Comment by Speiger** [comment]
This version is the development version.
1.19.2-43.1.47

**Comment by pouchrat** [comment]
No dice. :( https://mclo.gs/7DhqIMU

**Comment by Speiger** [comment]
I will check it out and fix it if possible in a couple days.

Thanks for the report.

**Comment by Speiger** [comment]
Sorry for this 3 month delay.
I just updated to latest 1.19.2 forge and started it and it just worked fine.

**Comment by Speiger** [comment]
Ok we found the issue, it will be addressed very soon.

**Comment by cactusdualcore** [comment]
I am currently suffering from this issure too, tried with only scavenge with forge-43.2.8 for 1.19.2 and it crashed, same error as above

> Ok we found the issue, it will be addressed very soon.

Out of curiosity, what and where is it?

**Comment by Speiger** [comment]
Forge made a breaking change in a version.
Technically if you run on the recommended version of forge it works fine :)

**Comment by Speiger** [comment]
Patch was submitted to cf and should be out very soon.
