### ISSUE TITLE
JEI GUI

### ISSUE THREAD

**Issue by TimGoll** [TinyModularThings/Scavenge#4]
Scavenge V1.12-1.8.3.2

![image](https://user-images.githubusercontent.com/13639408/46581250-c612d300-ca35-11e8-9820-6e260af10c1d.png)

The JEI GUI looks a bit off and I'd recommend to rework it completely. Remove the two tabs and only display the most important information directly. Also an icon would be cool. If you need some textures or icons, feel free to ask me

**Comment by Speiger** [comment]
@TimGoll how do you define "most important" information? Because these informations can be provided by the scripter itself. So i can't say "Conditions" are not important because all of them are.
The gui resize yeah thats a issue.

**Comment by TimGoll** [comment]
I get your point. At least for me, the most important information are: tool, input, output. The same like yours. But I don't get why the arrow has a dark grey background when all effects are hidden.

I update my issue:
- An icon would be cool
- fix the size
- move the two buttons to the right and make the square, hide them instead of greying them out
- remove the dark shadows on the arrow and the input square

**Comment by Speiger** [comment]
Yeah then disable the inputs and the buttons gray out and they know all the visible stuff is what they need.

about the things:
- Icon: Yeah sadly i am not an artist and i kinda want to prevent that the eyes of people start to bleed. (I am that bad at art)
- Fix the size: Yeah i am aware and its obviouse.
- Yeah as icon buttons are so easy to implement well and also deliver easily the "What they mean" information. Its text for a reason, also artist thing.
- You know i have eyes too.

Anything else?
