### ISSUE TITLE
1.16.5 crash

### ISSUE THREAD

**Issue by AlleCraft-alterego** [TinyModularThings/Scavenge#8]
forge : 36.1.0
scavenge : 2.0.1

i have made a istance with only scavenge mod..... this is crash log
[latest.log](https://github.com/TinyModularThings/Scavenge/files/6702473/latest.log)

**Comment by Speiger** [comment]
Yeah ok i fucked up the version system. Its going to be fixed today.
I wanted to automate that.

**Comment by Speiger** [comment]
Patch is released.

**Comment by AlleCraft-alterego** [comment]
thaks !
